export const FETCH_SCENE_PACKS_REQUEST = 'FETCH_SCENE_PACKS_REQUEST';
export const FETCH_SCENE_PACKS_SUCCESS = 'FETCH_SCENE_PACKS_SUCCESS';
export const FETCH_SCENE_PACKS_FAILURE = 'FETCH_SCENE_PACKS_FAILURE';

export const UPLOAD_SCENE_PACK_REQUEST = 'UPLOAD_SCENE_PACK_REQUEST';
export const UPLOAD_SCENE_PACK_SUCCESS = 'UPLOAD_SCENE_PACK_SUCCESS';
export const UPLOAD_SCENE_PACK_FAILURE = 'UPLOAD_SCENE_PACK_FAILURE';

export const FETCH_TUTORIALS_REQUEST = 'FETCH_TUTORIALS_REQUEST';
export const FETCH_TUTORIALS_SUCCESS = 'FETCH_TUTORIALS_SUCCESS';
export const FETCH_TUTORIALS_FAILURE = 'FETCH_TUTORIALS_FAILURE';

export const UPLOAD_TUTORIAL_REQUEST = 'UPLOAD_TUTORIAL_REQUEST';
export const UPLOAD_TUTORIAL_SUCCESS = 'UPLOAD_TUTORIAL_SUCCESS';
export const UPLOAD_TUTORIAL_FAILURE = 'UPLOAD_TUTORIAL_FAILURE';

export const FETCH_EDITIN_TOOL_REQUEST = 'FETCH_EDITIN_TOOL_REQUEST';
export const FETCH_EDITIN_TOOL_SUCESS = 'FETCH_EDITIN_TOOL_SUCESS';
export const FETCH_EDITIN_TOOL_FAILURE = 'FETCH_EDITIN_TOOL_FAILURE';

export const FETCH_USER_FEEDBACKS_REQUEST = 'FETCH_USER_FEEDBACKS_REQUEST';
export const FETCH_USER_FEEDBACKS_SUCCESS = 'FETCH_USER_FEEDBACKS_SUCCESS';
export const FETCH_USER_FEEDBACKS_FAILURE = 'FETCH_USER_FEEDBACKS_FAILURE';

export const FETCH_PROJECT_FILE_REQUESTB = 'FETCH_PROJECT_FILE_REQUEST';
export const FETCH_PROJECT_FILE_SUCCESS = 'FETCH_PROJECT_FILE_SUCCESS';
export const FETCH_PROJECT_FILE_FAILURE = 'FETCH_PROJECT_FILE_FAILURE';

export const FETCH_ANIME_RAWS_REQUEST = 'FETCH_ANIME_RAWS_REQUEST';
export const FETCH_ANIME_RAWS_SUCCESS = 'FETCH_ANIME_RAWS_SUCCESS';
export const FETCH_ANIME_RAWS_FAILURE = 'FETCH_ANIME_RAWS_FAILURE';

export const UPLOAD_ANIME_RAW_REQUEST =  'UPLOAD_ANIME_RAW_REQUEST';
export const UPLOAD_ANIME_RAW_SUCESS =  'UPLOAD_ANIME_RAW_SUCESS';
export const UPLOAD_ANIME_RAW_FAILURE =  'UPLOAD_ANIME_RAW_FAILURE';

export const UPLOAD_FEEDBACK_REQUEST = 'UPLOAD_FEEDBACK_REQUEST';
export const UPLOAD_FEEDBACK_SUCCESS = 'UPLOAD_FEEDBACK_SUCCESS';
export const UPLOAD_FEEDBACK_FAILURE = 'UPLOAD_FEEDBACK_FAILURE';