export const FETCH_SCENE_PACKS_REQUEST = 'FETCH_SCENE_PACKS_REQUEST';
export const FETCH_SCENE_PACKS_SUCCESS = 'FETCH_SCENE_PACKS_SUCCESS';
export const FETCH_SCENE_PACKS_FAILURE = 'FETCH_SCENE_PACKS_FAILURE';

export const UPLOAD_SCENE_PACK_REQUEST = 'UPLOAD_SCENE_PACK_REQUEST';
export const UPLOAD_SCENE_PACK_SUCCESS = 'UPLOAD_SCENE_PACK_SUCCESS';
export const UPLOAD_SCENE_PACK_FAILURE = 'UPLOAD_SCENE_PACK_FAILURE';

export const FETCH_TUTORIALS_REQUEST = 'FETCH_TUTORIALS_REQUEST';
export const FETCH_TUTORIALS_SUCCESS = 'FETCH_TUTORIALS_SUCCESS';
export const FETCH_TUTORIALS_FAILURE = 'FETCH_TUTORIALS_FAILURE';

export const UPLOAD_TUTORIAL_REQUEST = 'UPLOAD_TUTORIAL_REQUEST';
export const UPLOAD_TUTORIAL_SUCCESS = 'UPLOAD_TUTORIAL_SUCCESS';
export const UPLOAD_TUTORIAL_FAILURE = 'UPLOAD_TUTORIAL_FAILURE';